import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}</body>
    </html>
  );
}

import Footer from "@modules/layout/templates/footer"
import Nav from "@modules/layout/templates/nav"
import Providers from "@modules/providers"
import "styles/globals.css"

export default async function Page({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="relative">
            <Nav />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html